### ISSUE TITLE
Give BG & JA read access to logs stored on Cloudwatch

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#1011]
Jen & Ben are currently unable to access the archived logs for CMR in cmr-log S3 bucket

We would like to have IAM roles that allow us read access for cmr-log bucket

Would be useful to discuss IAM roles further for AWs services.

**Comment by glassresistor** [comment]
The cmr-log bucket was built by @joduinn by hand so that we don't lose the logs.  Longterm(this month) I'll be making the cmr-prod-log bucket(and stage/etc.) and have cloud watch pointed out to them.  Once that happens we will not need direct access to the bucket.  In the shortrun the size of the papertrail logs has been increased and I hope that should suffice for the next 2-4weeks.

In terms of general IAM access I have a plan and some tickets in the works to generate roles for developers.  Since our first move will just be s3 and RDS the roles django will have access to should also be enough for a devloper(r/w on buckets and the postgres user credentials).  If people prefer I can start by just copying those permissions over for each developer.

Longterm once everything is on lambda and built by ansible.  Developers, including myself, will likely not *need* much direct access to production systems and we should be able to mediate all changes to a systems via Ansible.   Exactly how we will do this is a near-future discussion.

**Comment by bengolder** [comment]
Okay, it sounds like maybe we should discuss further outside of this GH issue. In any case we still need read access to logs stored in AWS.  I'll modify this issue to be just the minimum issue needed (read access to logs stored in AWS).

**Comment by bengolder** [comment]
Modifying this per a Slack conversation w @glassresistor to focus on setting up read access for Cloudwatch. Pushing back the expected shipping time for this so we can have readable logs on Cloudwatch in the next 4 weeks.

**Comment by glassresistor** [comment]
Agreed to wait to do this when we get cloudwatch setup as per conversation with @bengolder
