### ISSUE TITLE
Timeout happening on followups-autocomplete

### ISSUE THREAD

**Issue by jennifermarie** [codeforamerica/intake#1046]
The following error is happening occasionally when staff users do a search via followups-autocomplete:

```
[Django] ERROR (EXTERNAL IP): Internal Server Error: /followups-autocomplete/

Internal Server Error: /followups-autocomplete/

SystemError at /followups-autocomplete/ <built-in function utf_8_decode> returned a result with an error set
```

This is erroring out when the request to the database is taking too long. This behavior began after we moved the database from Heroku add-on to AWS RDS.

**Comment by bengolder** [comment]
The ticket below implies that the error might be based on a timeout when requesting results from the database. This aligns with the fact that the error is only showing up on single letter autocomplete queries on followups (which would return a ton of results), and matches the metrics for that query in New Relic.

https://github.com/psycopg/psycopg2/issues/551

Short-term fix ideas (immediate):
- don't query for one letter, wait for two

Longer-term (months):
- switch to a more performant search backend
- move the app to AWS so there is less latency (I'm assuming the lag is caused by newly introduced latency, but haven't checked.)

**Comment by bengolder** [comment]
This is deprecated through the resolution of the RDS instance configuration
