### ISSUE TITLE
Move to clearmyrecord.org

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#1093]
Begin to use clearmyrecord.org as a primary domain name.

- [ ] transfer dns management to AWS & point clearmyrecord.org at the appropriate IP
- [ ] Move SSL certificate management to AWS
- [ ] adjust DNS so that clearmyrecord.codeforamerica.org redirects to clearmyrecord.org

This is valuable for adding functionality for handling incoming emails using mailgun and for putting a CDN in front of our static assets.

**Comment by glassresistor** [comment]
I've transfered the clearmyrecord.org to the cmr specific Amazon account 2 weeks ago to set up metabase.clearmyrecord.org  We ran into an issue where it wasn't showing the Amazon nameservers.  This is solvable just worth noting.

We can't transfer the SSL certificates to being managed by the Amazon ACM until we move our application servers to AWS.  This is because to use the ACM you must be able to automatically update the certificates used by the application server, which Heroku doesn't have a way to do with the AWS ACM.  Luckily this isn't a blocker and we can just use the Heroku ACM, which is a single click.

In terms of dns we need to setup I believe these are the steps we need to take.  It had extra complexity because we use an old SSL addon and will need to update the Heroku ACM at the same time.
- [ ] clearmyrccord.org returns Amazons Nameservers
- [ ] clearmyrecord.org redirects to www.clearmyrecord.org
- [ ]  www.clearmyrecord.org should cname to www.clearmyrecord.org.herokudns.org
  - [ ] requires adding  the new domain on heroku
- [ ] stage.clearmyrecord.org should cname to stage.clearmyrecord.org.herokudns.org
  - [ ] requires adding the domain on heroku
- [ ] Setup MX records for email servers(Mailgun?)
  - [ ] Update applications email alerts domains
- [ ] Update Production and Staging settings files to allow for the new domains
- [ ] Make sure no urls in the application are hard coded and update the sites section in the Django Admin
- [ ] In Production and Staging turn on Heroku ACM and the remove the old SSL add-on
- [ ] clearmyrecord.codeforamerica.org redirects to www.clearmyrecord.org

**Comment by glassresistor** [comment]
While working the on  AWS migration roadmap I realized waiting to move staging and production over to the new domain would make sense.

when we migrate the application instances over we will for a peroid of time need to run both Heroku and the new instances while DNS swaps over.  If we make the new sites on the new domain and then just turn the old CMR address into a redirect it swap over faster.

We also will need to setup SSL for the new domain and if we just swap the new site over we can avoid this headache.

**Comment by bengolder** [comment]
A note on the checklist: `Setup MX records for email servers(Mailgun?)` is something we will probably do eventually, but is outside the scope of this ticket. No need for it now.
