### ISSUE TITLE
Easy Audit is missing migrations

### ISSUE THREAD

**Issue by glassresistor** [codeforamerica/intake#1111]
While working on getting the database to sync I ran into an issue with @rossettistone 's easyaudit fork.

From a rough glance it looks like you need to run makemigrations and commit the changes.

You can see when I run makemigrations it creates them within the package itself.

```bash
./manage.py migrate
Operations to perform:
  Apply all migrations: account, admin, auth, clips, contenttypes, easyaudit, intake, invitations, partnerships, sessions, sites, socialaccount, taggit, user_accounts
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

(intake) 
┌───=[ mikela :: slimemold -( 0 )-[ ~/code/intake ]
└──(./manage.py makemigrations
Migrations for 'easyaudit':
  /home/mikela/.conda/envs/intake/lib/python3.5/site-packages/easyaudit/migrations/0006_auto_20170829_2002.py:
    - Alter field event_type on crudevent
    - Alter field user_pk_as_string on crudevent
    - Alter field login_type on loginevent
```

**Comment by bengolder** [comment]
This is an issue in easyaudit's library. It appears to be a difference between whether `makemigrations` is run in a Python 2.7 vs Python 3 environment. In 2.7, no migration is generated. In Python 3, it defines the `choices` labels on various fields as `bytestring` literals instead of strings, thus creating `AlterField` migrations that change labels for `choices`. This migration would not change the database, but would likely affect handling of choices for any manual input of CRUDEvent objects or HTML display of CRUDEvents. Since we do not include CRUDEvents in the admin , or offer any manual ways to edit them, nor display them in any UI, I'm inclined to lower the priority of this issue.
