### ISSUE TITLE
Create alerts for Cloudwatch [1]

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#1164]
- unusual 5xx errors
- unusual 4xx errors
- significant access changes

**Comment by lkogler** [comment]
Set alerts (for Lambda):
- Error rate
- Latency
- Traffic spikes
- DB latency
- IOps

Possibly Sentry might make this easier

**Comment by glassresistor** [comment]
First steps to doing this is doing a bit of research on my part for adding these using Ansible/AWS cli since we will have to set this up each time we deploy a new system or migrate from one infrastructure version to another.

Should be pretty simple.  I'll try for a simple alert like alert us if the database is down.

**Comment by glassresistor** [comment]
So I've managed to setup Alarms for the production database by hand.

High Production Write Latency
High Production Read Latency
High Production Read IOPS
High Production Write IOPS
Too Many Database Connections(>40 for 3mins)
High Production CPU Usage(>90% for 5min)

Error Rate and Application latency are something I'll need to work out with Lambda on the development account.  

So far my feeling is that adding Sentry will just add work and not get us anything meaningful.

**Comment by glassresistor** [comment]
I've also made an event subscription for RDS which should alert us if one of many actions has happened that would mean the production database is down.
