### ISSUE TITLE
Pre-filled pdf button is filling non-SF applications with SF's PDF

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#1297]
"Pre-filled PDF" button should only appear on San Francisco applications. 

I opened an application for EBCLC and Contra Costa PD and saw the "pre-filled PDF" button on the top of the page. When I clicked on that button, it went to San Francisco's pre-filled PDF, incorrectly filling a San Francisco Public Defender's Office PDF with an applicant's information who did not apply in San Francisco.

See https://clearmyrecord.codeforamerica.org/application/3249/ and click on "Pre-filled PDF" button.

**Comment by lkogler** [comment]
Note: This issue only affects CfA users. The current behavior is that the PDF feature is turned on/off by user, not based on the individual app you are viewing. So in order for CfA users to be able to see/debug SF PDFs, all "staff" users have the feature turned on.  

The PDF button is not visible for users from other orgs besides SF Public Defender and CfA.

It would take a non-trivial amount of work change the behavior so that CfA users would only see the PDF button for SF applications. My recommendation is that it is not worth prioritizing at this time. Can we close this issue @TiffanyAndrews?

**Comment by TiffanyAndrews** [comment]
@lkogler I agree. It is not a priority at this time to change the behavior for CFA users.
