### ISSUE TITLE
Investigate session errors

### ISSUE THREAD

**Issue by lkogler** [codeforamerica/intake#1359]
We are seeing the errors "No counties in session data" and "No applicant in session data" at a rate of a few per day. This is an error that will occur if someone visits a page after the county selection in the application process (either /application or /review), but doesn't have the necessary data in their session, so they will get redirected back to the beginning.

**Comment by glassresistor** [comment]
We've setup metric filters to graph occurrences and updated the logs to include more information.

**Comment by glassresistor** [comment]
On friday I looked at multiple logs of user behavior and so far it all looks either like its the first time this person has gone to the new CMR site or someone who hit the back button or book marked the page.

Its my belief this started recently both because of the domain change but mainly because users are now bookmarking the review page thinking they can come back later.
