### ISSUE TITLE
Deprecate ApplicationLogEntry

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#152]
#### Non destructive
- [x] co-recording events as both log entries and ApplicationEvents
- [x] Make the application states in some way #151 
- [x] Evaluate whether applicationlogentry could be replaced with attributes on the formsubmission or applicant table
- [x] making sure we have events that adequately cover the scope of ApplicationLogEntry
- [x] copying data (as migration or script) from ApplicationLogEntry into ApplicationEvent
#### Destructive
- [x] making sure our logic uses application events instead of ApplicationLogEntry
- [ ] Deleting all references to ApplicationLogEntry

**Comment by rossettistone** [comment]
From convo with @bengolder, this issue is almost entirely deprecated. ApplicationLogEntry and ApplicationEvent both were refactored out of use, and their functionality has been replaced by a combination of mixpanel events, logging, and status notifications.

The remaining task to close this would be to fully remove the now-unused ApplicationLogEntry and ApplicationEvent models.
