### ISSUE TITLE
Remove mixpanel

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#180]
We decided not to use mixpanel. Let's take it out.

**Comment by loumoore** [comment]
hey @bengolder i was about to finally do this ticket, but on second thought i think it might be worth keeping mixpanel in there. i see it's tracking your event data already. i think that might turn out to be useful even though we are not using it for your dashboard, because with mixpanel we can do segmentation and dive into the data more easily if other questions come up, and we can easily add new events that might not necessarily belong in your dashboard.

lemme know what you think, we can discuss in person after the holidays.
