### ISSUE TITLE
Move logic into services layer

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#209]
Most of the query setup and logic is split between views and model methods.

These methods should be gradually converted into functions that sit in services modules.

This is done when none of the models contain significant logic in their methods.

**Comment by glassresistor** [comment]
I'd be interested in looking at this.  It sounds like instead of moving the query construction into services it would be better to do it on the appropriate model as a manager.  Model managers are the Django native tool for building querysets.  

Services are a good way to organize a bunch of utils but its more inline with the django philosophy to keep queries within the models framework itself.

Doing it this way should both be more powerful/easier and be easier for another develop onboarding since its a documented feature of the framework
