### ISSUE TITLE
Integrate "People we served" spreadsheet into CMR and delete it

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/intake#397]
We should discuss the best way to do this - want to make sure that notes are added properly and that we at least add status tags to the applications we know for sure

**Comment by bengolder** [comment]
In order to pull in the historical "people we served" spreadsheet, we need to have three columns:

1. The form submission ID, the one used for pulling up the detail page in the app
2. a column with any comma-separated tags we want to link to this app
3. A column with notes we want to add

Optional & helpful:
- date and name columns for the notes, so we can see when the notes were taken, and who added them (presumably all Jazmyn)

**Comment by bengolder** [comment]
In order to be able to pull comparative before & after stats for status notifications, I'm going to try loading this spreadsheet.

**Comment by bengolder** [comment]
This is done. I just need to confirm the results with @jazmynlatimer before adding to the production database

**Comment by bengolder** [comment]
This is done and the spreadsheet is ready for deletion.

**Comment by bengolder** [comment]
deleted
