### ISSUE TITLE
Audit the set of alerts we get for user activity and see if additions/subtractions are needed.

### ISSUE THREAD

**Issue by jennifermarie** [codeforamerica/intake#504]

**Comment by rossettistone** [comment]
First step here is to make a list of all user actions and determine which ones we want to set alerts for. Given the move to support mode, our needs on alerting may soon be changing, so we should keep that in mind. We should show a tentative list to Tiffany and others who are likely to be consumers of those alerts for their approval.

**Comment by bengolder** [comment]
## Proposed Changes to Alerts

_BLUF: We recommend mostly removing unimportant alerts so that significant events are more visible, and adding some new alerts for security monitoring._

@lkogler, @glassresistor, & I looked at the set of alerts that exist for user actions and propose the following changes. We still log most user activity in mixpanel for performance and usage monitoring, so we decided to focus on alerts posted in slack and email.

In `#clearmyrecord-alerts`:
- Keep the daily new apps summary showing how many apps are unopened or in need of status updates by each org
- Continue posting any emails to `clearmyrecord-alerts@codeforamerica.org` to show any production bugs or urgent issues.
- Remove slack messages about follow ups being sent #1260 
- Remove slack messages about apps being opened. #1260 
- Remove slack messages about each new application #1260 
- Add an alert when an org stops using CMR (hasn't opened any apps/logged in 20 days) #1262
- Add an alert when someone logs in as a superuser #1257 
- Add an alert when new users are created #1258 
- Add an alert when there are too many failed login attempts, use a high threshold #1259 

Delete the `#clearmyrecord-dev` slack channel #1260 because it does not seem to be helpful.

@TiffanyAndrews & @jazmynlatimer please review these changes and let us know if you approve or want any changes. Happy to discuss in person if that's easier.

Talked to @jazmynlatimer in person, she gave a 👍

**Comment by TiffanyAndrews** [comment]
The only change is below in **bold**: 
Add an alert when an org stops using CMR (hasn't opened any apps/logged in **20 days**)

**Comment by bengolder** [comment]
Closing this ticket. All alerts and work originating from this have been broken into separate tickets. Assessment is complete.
