### ISSUE TITLE
Research & scope the possibility of relaying communications

### ISSUE THREAD

**Issue by TiffanyAndrews** [codeforamerica/intake#603]
Large county user's work email address will replace the default cmr email address, when user is logged in and send out a status notification. 

(for agencies with 3+ unique user)

**Comment by bengolder** [comment]
There are a few ways to implement this:
- providing a different "from" email (not sure if this is easily possible)
- using CC
- relaying messages

Since this is an exploratory feature, we will use CC for now because that is the easiest. (we can add a flag for user profiles to determine if they should be CC'd or not).

**Comment by bengolder** [comment]
While CC seemed like a good temporary solution, upon deeper examination, I can see that it would be incomplete. I'm not sure how we could effectively CC on text messages, and therefore we would only be able to add a CC email in cases where the notification was being sent via email. An improvement, but an incomplete and possibly misleading one.

It seems like we should look at the possibility of relaying messages in order to fully address this need.

**Comment by bengolder** [comment]
Draft of brief here:
https://docs.google.com/a/codeforamerica.org/document/d/1Fz2scDYuPHZT1Nfd69ifQVX2UzfTQ34e0ReLaVBKa-4/edit?usp=sharing
