### ISSUE TITLE
set expiration date for postgres backups

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#609]

**Comment by bengolder** [comment]
@glassresistor is this done?

**Comment by glassresistor** [comment]
Turns out Heroku does this for us in a useful way.  

Scheduled backups retention limits

Scheduled backups have a different retention policy as compared to the manual backups. This policy is also based on the database plan. For all plans, a daily backup is retained for the last 7 days. That means that 7 backups will exist, one for each of the last 7 days. A weekly backup means that only one backup is saved over a 7 day period. A monthly backup means that only 1 backup is saved over the course of a month. Based on current limits, for example, a Premium-0 would have 12 monthly backups, one for each of the last 12 months.
Plan 	Weekly Backups Retained 	Monthly Backup Retained
Hobby-Dev 	1 week 	0 months
Hobby-Basic 	1 week 	0 months
Standard-* 	4 weeks 	0 months
Premium-* 	8 weeks 	12 months
Enterprise 	8 weeks 	12 months
