### ISSUE TITLE
Document role onboarding, offboarding procedures, process for role change requests

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#653]
Audience, a tech-literate person seeking to clarify whether or not Clear My Record and it's administration are secure.

Sketch of roles:
- tech admin
- CfA management (need to monitor product performance and get detailed insights)
- customer service staff (followups, intercom chat)
- org users who help applicants (lawyers/public defenders)
- applicants (people who apply, no login)

**Comment by glassresistor** [comment]
Latest description of roles is here: https://www.notion.so/cfa/Information-Access-Roles-409a9f04b9494392a7e96653f6781f51

Next Steps:

1.  Ben write up who has what role and any deviation from that role.
2.  Ben and Mikela meet go over those roles and make suggested changes.
3.  Write preferred new roles.
4.  Ben and Infra staff will communicate(via meeting) upcoming changes to all.
5.  Implement new roles.

**Comment by glassresistor** [comment]
@bengolder please follow up with step 1 and readd me when starting step 2

**Comment by glassresistor** [comment]
@bengolder as per meeting I've gone ahead and made a 2nd section with potential new roles.  I feel good about it in terms of a infrastructure access but am missing things related to application user roles and user onboarding.  I would ultimately like to reduce who has superuser and role management because it is hard to separate that from complete access to any data that any user could get.  I currently don't know much about how Legal Assisters are on-boarded and if that can be done by another user in there organization or another role which will already has access to that data.

**Comment by glassresistor** [comment]
@bengolder and I met to discuss the current state of the draft roles.  The next steps are to define who has which current roles and will have them in after the proposed changes.

The main changes in the draft include
1.  Reducing database and server access to the Infrastructure role(myself, Jon, Jen, and Ben)
2.  Limiting who has Django Superuser.
3.  Limit who can arbitrarily manage users.
4.  Minor changes to who has 3rd party access.
