### ISSUE TITLE
Make static() fail on bad path in jinja using default Stagtic File Storage

### ISSUE THREAD

**Issue by glassresistor** [codeforamerica/intake#767]
Heroku whitenoise fails loudly if a staticfile mentioned with static(...) is called in template at runtime but the basic file storage fails silently.

We should probably either use whitenoise on development or go ahead and migrate to using s3 for static files on heroku (much faster).

Its odd that the behavior is different  but as far as I can tell this is specific to the jinja static function

**Comment by bengolder** [comment]
Turning Whitenoise back on for local development works for me (it was previously on, but I think we removed it due to troubles with old, outdated, local selenium tests).

If we move back to S3, I think it would be worth checking that setup against these points, which originally convinced me to move from S3 to Whitenoise: http://whitenoise.evans.io/en/stable/#infrequently-asked-questions

**Comment by glassresistor** [comment]
I think ultimately we should move to S3 for points that we talked about,  I would really rather we not use whitenoise locally since it makes debugging more confusing.

The main issue is that the static function should fail no matter what environment its running on.  So the main issue is that django-jinja implements static improperly.  I think the most preferable solution is simply to fix the static() implementation.

I think a likely fix would be to move from using django-jinja to djangos built in jinja template engine and upgrade to django 1.11
