### ISSUE TITLE
Update deployment steps checklist

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#836]
We have a list of steps for deploying here:

https://www.notion.so/cfa/Release-Deployment-Management-141c27fc07b54917b512705b4faa070b

And we have a new step to add with the merging of 
https://github.com/codeforamerica/intake/pull/811

When new fixtures are being merged into `develop` or `master`, it's necessary to run `heroku run ./manage.py new_fixtures --app cmr-develop/deploy`

**Comment by glassresistor** [comment]
Small adendum.  new_fixtures only needs to be run if you add/rm or change data.  If you change a schema you will have to update the fixtures for tests but there is no reason to run new_fixtures on demo/develop because the migrations should handle it and if fact its best to test migration can handle it.
