### ISSUE TITLE
June 6th Request timeouts

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#920]
```
Jun 06 07:28:34 cmr-prod heroku/router:  at=error code=H12 desc="Request timeout" method=GET path="/applications/bundle/911/" host=clearmyrecord.codeforamerica.org request_id=fbbd4390-f901-4e8d-a7e0-a3b8796b0480 dyno=web.2 connect=1ms service=30001ms status=503 bytes=0 protocol=https 
Jun 06 07:29:32 cmr-prod heroku/router:  at=error code=H12 desc="Request timeout" method=GET path="/applications/bundle/911/" host=clearmyrecord.codeforamerica.org request_id=d1a54176-e5b9-48c1-80a0-4f0f0af75323 dyno=web.1 connect=2ms service=30000ms status=503 bytes=0 protocol=https
```

**Comment by bengolder** [comment]
I've looked at the logs around these events and can't find the precise cause. Right before it crashed, it was logging a mixpanel event for each app in the bundle. Additionally there were maybe two other users active on the site, one applying and the other viewing individual applications

**Comment by bengolder** [comment]
I was able to open the page. The logs show another timeout in the midst of the calls to mixpanel, but I did not see any errors in the browser. This might have something to do with the size of the worker queue or the number of queries needed to create each mixpanel task

**Comment by glassresistor** [comment]
I took a look at the https://github.com/codeforamerica/intake/blob/master/intake/views/admin_views.py#L125-L149

Its making  ~5 or 6 different queries one of them an update, 1 call to mix panel per submission, and is not creating any tasks.

I think it would be good to tune the queries here so that we make fewer and run mark_open service as a task(one task for all submissions).

We should also run of the  the MixPanel calls as a task.  We should run one task per submission unless we need them to happen in sequentially then all in one task.
