### ISSUE TITLE
NewApps PDF may disappear on refresh

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/intake#961]
I think the current implementation of the NewApps PDF was intended to work in the following steps:

1. Org user opens an email that links to the unread apps index page
2. They click the link and arrive at the unread apps tab
3. They click a button labelled "Print all"
4. A page loads with:
    - a PDF showing all the unread apps
    - a flash message notifying the user that these applications have now been marked as "Read"

At step 4, we mark the set of unread applications as "read", which leads to clearing the "unread apps" PDF.
If a user refreshed the page at step 4, the PDF may disappear, because once they've opened the set of applications on the first click, those applications are no longer "unread". In early versions of Clear My Record, we encountered this problem. Staff at the SF public defender would refresh a page and the apps would no longer be available in the unread apps PDF. They perceived this as an error and reported that they could not download PDFs.

Here are some options for how we can manage this risk.
**Note that these options are not always exclusive of each other, but they are all different approaches to solving the core problem**

**1. Proceed but keep a close watch**
add a special Mixpanel events to mark when an empty new apps PDF is sought. Add help text to the empty page that prompts them to contact us if they felt they reached the page in error

_Pros_
- We know if it's breaking for people

_Cons_
- PDF can disappear on refresh

**2. Use a download link instead of a new page**
Clicking on "Print all" initiated a download instead of opening a window

_Pros_
- less likely that the user would reinitiate the download before letting the download complete

_Cons_
- Would have to either use AJAX or a JavaScript initiated page refresh to notify the user that the apps have been marked as "Read"
- If anything interrupted the download, the apps would still be marked as read and they would not be able to recover the same PDF
- We may not be able to implement this, it depends on how different browsers handle file downloads

**3. Adding a delay before invalidating the new apps pdf**
When the new apps PDF is opened, we will initiate task to mark the apps as "read" and then rebuild the new apps PDF according to the number of unread apps (likely 0 in this case). We could add a delay to the task of invalidating the PDF

_Pros_
- the user could refresh page for a certain window of time without the PDF disappearing.

_Cons_
- if other apps are opened or submitted, they will initiate their own tasks to rebuild the PDF, so the delay might be overwritten by a new app or opening an individual app.
- creates a complex set of asynchronous tasks that change state, makes it hard to keep track of state.

**4. Separate the actions of printing and marking as read**
Added a separate button to mark the apps as read

_Pros_
- user can refresh page without consequences and download or print the PDF however they choose.
- based on explicit user actions

_Cons_
- Adds an extra click
- Past experience shows us that there is a risk that they will not click a "Mark as read" button without a clear incentive.

**5. Keep all prebuilt PDFs (don't erase them)**
Instead of removing old PDFs, we would make new ones when we need to.

_Pros_
- This would allow users to refresh a page with PDFs indefinitely
- Links for any given PDF persist and can be shared where needed.

_Cons_
- ~3x increase in storage load

**Everything except for option 4 has one shared drawback:**
We can't be sure if an app was lost or not (if it's accidentally marked as "Read"). In the case of SF, they are less likely to visit the other tabs and find missing apps.

**Comment by jennifermarie** [comment]
Thanks @bengolder for writing this up!

Some thoughts: *Solution 4 is the only one that is truly an explicit receipt* -- the others rely on passive/implicit receipt actions, and don't really seem to solve what we're trying to solve.

The user story that is rolling around in my head over this is as follows:
- A team member who is one of many users with an account from an org (let's call him Alan) could receive the email with the new apps page link/download link/etc. and click on it to see what's there. That same link is also in the inbox of his teammates, he's just the first to click it.
- In solutions 1 - 3, that link leads to a view of some kind -- not an actual print action per se. It would mark the apps as read, even if Alan does not print the combo PDF.
- Another attorney from the org (let's say, Betty) may wish to print the unhandled apps in bulk later.
- She can't, because the newapps PDF has been refreshed and now only contains apps that weren't in the batch Alan marked read (implicitly, by opening the link) that morning.

The reason I like solution 4 is because if Alan clicks the link and realizes that he's not going to be handling all of these apps today, he isn't taking away the printable batch of PDFs from Betty. If he chooses to mark them as read, it's clear to him/his team that they're being handled. Less chance to lose apps in the shuffle.
